// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv src/worker-configuration.d.ts`

interface CloudflareEnv {
	GREEN_STATE: KVNamespace;
	MARKET_CACHE: KVNamespace;
	SUPABASE_URL: "https://pvbcdndqjguzqeafhwhw.supabase.co";
	AI: Ai;
}
